// <auto-generated />
namespace Groomers.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class personFKtoappointments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(personFKtoappointments));
        
        string IMigrationMetadata.Id
        {
            get { return "202004072104166_person FK to appointments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
